<template>
    <b-navbar variant="danger" fixed="bottom" type="dark"  class="sticky-bottom">
        <b-navbar-nav>
            <b-nav-item style="font-size:.85rem"> <span>©</span> Copyrights 2019. All rights reserved.</b-nav-item>
        </b-navbar-nav>
        <b-navbar-nav class="ml-auto">
            <b-nav-item>
                <router-link to="/" class="text-white">Career</router-link>
            </b-nav-item>
            <b-nav-item>
                <router-link to="/" class="text-white">Contact us</router-link>
            </b-nav-item>
            <b-nav-item>
                <router-link to="/" class="text-white">Press Center</router-link>
            </b-nav-item>
            <b-nav-item>
                <router-link to="/" class="text-white">Help</router-link>
            </b-nav-item>
        </b-navbar-nav>
    </b-navbar>
</template>
